version: "3.8"

services:
  app:
    build: .
    container_name: lost-middle-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

volumes:
  ollama:
