blank_issues_enabled: false
contact_links:
  - name: Questions and general help
    url: https://github.com/Jefino9488/lost-middle-analyzer/discussions
    about: Ask questions, share ideas, or get help here.
